### ISSUE TITLE
Full runnable CDK deploy example

### ISSUE THREAD

**Issue by bdon** [OvertureMaps/overture-tiles#7]
Right now only the constructs file is in git.

**Comment by bdon** [comment]
Closed by #11 - @charliemcgrady did you need to rename the bucket somehow?

**Comment by bdon** [comment]
I hardcoded that to a stable name here: https://github.com/OvertureMaps/overture-tiles/blob/main/overture-tiles-cdk/lib/overture-tiles-cdk-stack.ts#L39

**Comment by charliemcgrady** [comment]
Ah I pulled the changes before that was merged. I needed to update the bucket name manually with the new changes.

Is the goal to make this stack deployable to any AWS account, or just the Overture account? 

The current state of the repo solves the latter, but we would need to make things more generic for the former. I'd love to create a suite of CDK construct/stacks which enable users to easily generate / self-host tiles, but I'm not sure if this is the correct repository.

**Comment by charliemcgrady** [comment]
FYI I made the bucket/image configurable in https://github.com/OvertureMaps/overture-tiles/pull/18.

**Comment by charliemcgrady** [comment]
We're aligned on enabling deployment to every account.

One example of an assumption which does not apply to every use-case is [the public bucket configuration](https://github.com/OvertureMaps/overture-tiles/blob/main/overture-tiles-cdk/lib/overture-tiles-cdk-stack.ts#L38). Over time, we could refactor the OvertureTilesCDKStack into multiple constructs (i.e. `TileGenerationJob`, `TileDistribution`, `ImageRepository`, etc) so that folks can pick and chose the components they'd like to use. For now, I think props are sufficient.

**Comment by bdon** [comment]
Should we make the public-ness of the bucket configurable? `isPublic: boolean`
